using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoMVC.Models
{
    [Table("PM_EmpCompanyProfile_Tbl")]
    public class EmployeeCompanyProfile
    {
        [Key]
        public int Emp_Id { get; set; }
        public int? EmpStatus_Id { get; set; }
        public int Designation_Id { get; set; }
        public int Team_Id { get; set; }
        public int Department_Id { get; set; }
        public int? Mentor_Id { get; set; }
        public int ReportsTo { get; set; }
        public int? Manager_ReportsTo { get; set; }
        public int EmpType_Id { get; set; }
        public int Shift_Id { get; set; }
        public int EmplyeeNumber { get; set; }
        public DateTime? DOJContract { get; set; }
        public DateTime DOJ { get; set; }
        public DateTime? DOJGratuity { get; set; }
        public DateTime? DOC { get; set; }
        public DateTime? DOE { get; set; }
        public string? UserName { get; set; }
        public string? Password { get; set; }
        public string? SkypeId { get; set; }
        public string? EmailId { get; set; }
        public string? TotalExp { get; set; }
        public bool? IsManager { get; set; }
        public bool? IsScoper { get; set; }
        public string? EncryptPassword { get; set; }
        public string? SaltKey { get; set; }
        public int? PreviousTeamID { get; set; }
        public string? PMPassword { get; set; }
        public bool? IsSupervisor { get; set; }
        public string? ResignationReason { get; set; }
        public string? ResignEmployeeComments { get; set; }
        public DateTime? ResignedOn { get; set; }
        public string? ExitWay { get; set; }
        public bool? NSAEligible { get; set; }
        public string? TerminationReason { get; set; }
        public bool? IsConfirmed { get; set; }
        public bool? IsReportingManager { get; set; }
        public string? TypeOfResource { get; set; }
        public DateTime? BillableFrom { get; set; }
        public bool? IntroducedtoClient { get; set; }
        public DateTime? IntroducedtoClientOn { get; set; }
        public int? ExtendedProbationPeriod { get; set; }
        public DateTime? ProposedDOC { get; set; }
        public string? ReasonforExtension { get; set; }
        public string? CareerPathTrack { get; set; }
        public int? Country_Id { get; set; }
        public int? CultureHouseId { get; set; }
        public int? SourceOfCandidateId { get; set; }
        public string? SourceOfCandidateComments { get; set; }
        public int? EurekaReviewManager { get; set; }
        public int? SecurityIncidentVerifier { get; set; }
        public bool? RetentionBonus { get; set; }
        public bool? ExitPrintOut { get; set; }
        public bool? ExternalAccess { get; set; }
        public bool? IsCultureCaptain { get; set; }
        public int? CultureCaptainRole { get; set; }
        public bool? IsFoodCommitteeMember { get; set; }
        public string? KPIScorePath { get; set; }
        public bool? BirthdayAlert { get; set; }
        public DateTime? AppraisalCycle { get; set; }
        public string? Grade { get; set; }
        public string? PreviousExp { get; set; }
        public bool? IsCabfacility { get; set; }
        public DateTime? B2KDOJ { get; set; }
        public DateTime? IncrementEffectiveDate { get; set; }
        public string? WorkingHours { get; set; }
        public DateTime? NSAFromDate { get; set; }
        public DateTime? NSAToDate { get; set; }
        public bool? IsKRAconfirmed { get; set; }
        public string? KRASheet { get; set; }
        public bool? Promotion { get; set; }
        public DateTime? LastPromotion { get; set; }
        public string? Location { get; set; }
        public int? LocationId { get; set; }
        public bool? IsCoEMember { get; set; }
        public int? ReferralId { get; set; }
        public bool? PMUsage { get; set; }
        public bool? DisableBiometric { get; set; }
        public bool? IsAgreeCompetency { get; set; }
        public bool? PBEligiblity { get; set; }
        public string? PBPayout { get; set; }
        public string? MandatoryMetricat_ME_RatingforPB { get; set; }
        public string? SalesforceId { get; set; }
        public string? ExtensionNo { get; set; }
        public string? FounderPhilosophy { get; set; }
        public DateTime? NDAStartDate { get; set; }
        public DateTime? NDAEndDate { get; set; }
        public string? ContractType { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public string? DesignationLevel { get; set; }
        public string? DesignationName { get; set; }
        public string? AppraisalComments { get; set; }
        public DateTime? PasswordChanged { get; set; }
        public int? PasswordInvalidAttempt { get; set; }
        public bool? AccountLock { get; set; }
        public string? MultifactorCode { get; set; }
        public DateTime? MultifactorSharedOn { get; set; }
        public DateTime? MultifactorVerifiedOn { get; set; }
        public DateTime? ResetPasswordLinkshared { get; set; }
        public int? SAP_Supervisor { get; set; }
        public int? SAP_TeamHead { get; set; }
        public string? ShiftTime { get; set; }
        public string? CurrentWorkLocation { get; set; }
        public string? OfficeCabAvailment { get; set; }
        public string? BangaloreAddress { get; set; }
        public string? Landmark { get; set; }
        public string? ResidencetoOfficeDistance { get; set; }
        public string? ContactNumber { get; set; }
        public string? PinCode { get; set; }
        public string? AreaName { get; set; }
        public string? ProfilePhoto { get; set; }
        public DateTime? PhotoUploadedOn { get; set; }
        public bool? ProfilePhotoApproved { get; set; }
        public int? ProfileApprovedBy { get; set; }
        public DateTime? PhotoApprovedOn { get; set; }
        public string? PhotoRejectedReason { get; set; }
        public string? VehicleType { get; set; }
        public string? VehicleMake { get; set; }
        public string? VehicleVariant { get; set; }
        public string? VehicleRegistrationNumber { get; set; }
        public string? VehicleColor { get; set; }
        public DateTime? TransportVerifiedOn { get; set; }
        public string? TShirtSize { get; set; }
        public string? VaccineCertificate { get; set; }
        public DateTime? CovidAffected { get; set; }
        public string? WFHReason { get; set; }
        public DateTime? WFHFrom { get; set; }
        public DateTime? ReturnedtoOffice { get; set; }
        public bool? CurrentlyUsingCab { get; set; }
        public string? Role { get; set; }
        public bool? ShiftAllowance { get; set; }
        public DateTime? NextAppraisalEligible { get; set; }
        public int? RoleResponsibilityID { get; set; }
        public bool? RoleResponsibilityStatus { get; set; }
        public DateTime? RoleResponsibilityOn { get; set; }
        public bool? RoleResponsibilityMentorBriefStatus { get; set; }
        public DateTime? RoleResponsibilityMentorBriefOn { get; set; }
        public int? RoleResponsibilityMentorBriefBy { get; set; }
        public bool? WFHStatus { get; set; }
        public double? AvailableWFH_Balance { get; set; }
        public DateTime? WomenConsentSignedon { get; set; }
    }
}
